export default function MethodologySection() {
  const trustSignals = [
    {
      icon: '🔒',
      title: 'Data Security',
      description: 'Enterprise-grade encryption for all data storage and transmission. SOC 2 Type II certified.',
    },
    {
      icon: '📈',
      title: 'Transparent Methodology',
      description: 'Open-source scoring algorithm. All factors and weights are publicly documented and auditable.',
    },
    {
      icon: '⚖️',
      title: 'Regulatory Compliance',
      description: 'Fully compliant with HKEX listing rules and SFC regulations. Not financial advice.',
    },
  ];

  return (
    <section className="py-16 bg-gradient-to-br from-gray-50 to-gray-100">
      <div className="container mx-auto px-6 max-w-7xl">
        <div className="text-center mb-12">
          <h2 className="text-3xl font-bold text-gray-900 mb-4">Methodology & Trust</h2>
          <p className="text-xl text-gray-600 max-w-3xl mx-auto">
            Built on rigorous quantitative research and transparent data analysis
          </p>
        </div>

        <div className="grid md:grid-cols-3 gap-8 mb-12">
          {trustSignals.map((signal, index) => (
            <div key={index} className="bg-white rounded-card p-8 shadow-card hover:shadow-card-hover transition-all duration-300 hover:-translate-y-1">
              <div className="text-5xl mb-4">{signal.icon}</div>
              <h3 className="text-xl font-bold text-gray-900 mb-3">{signal.title}</h3>
              <p className="text-gray-600 leading-relaxed">{signal.description}</p>
            </div>
          ))}
        </div>

        {/* Disclaimer */}
        <div className="bg-yellow-50 border-2 border-yellow-200 rounded-lg p-6 max-w-4xl mx-auto">
          <div className="flex items-start gap-3">
            <div className="text-3xl">⚠️</div>
            <div>
              <h4 className="font-bold text-gray-900 mb-2">Important Disclaimer</h4>
              <p className="text-sm text-gray-700 leading-relaxed">
                This platform provides quantitative analysis for informational purposes only. IPO scores and ratings are generated by algorithmic models and should not be considered as investment advice, recommendations, or guarantees of future performance. All investments carry risk, and past performance does not guarantee future results. Always conduct your own due diligence and consult with licensed financial advisors before making investment decisions.
              </p>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
